//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyInformationalVersion("ce7cd98baaa48b3b8c0ae169bf70c24de8304334")]
[assembly: System.Reflection.AssemblyFileVersion("6.6.2.3699")]


