//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyInformationalVersion("25b10c6da2ce73b83de15fe17e4f3859e681f438")]
[assembly: System.Reflection.AssemblyFileVersion("6.6.2.3693")]


