
rd/s/Q "ASCOM Platform Examples\ASCOM.DriverAccess Example\bin"
rd/s/Q "ASCOM Platform Examples\Examples\bin"
rd/s/Q "ASCOM Redirection Policies\ASCOM Redirection Policies\bin"
rd/s/Q "ASCOM.Astrometry\ASCOM.Astrometry\bin"
rd/s/Q "ASCOM.Astrometry\ASCOM.Astrometry556\bin"
rd/s/Q "ASCOM.Astrometry\EarthRotationUpdate\bin"
rd/s/Q "ASCOM.Attributes\bin"
rd/s/Q "ASCOM.Controls\ASCOM.Controls\bin"
rd/s/Q "ASCOM.Controls\ASCOM.Controls.Demo\bin"
rd/s/Q "ASCOM.DeviceInterface\bin"
rd/s/Q "ASCOM.DriverAccess\bin"
rd/s/Q "ASCOM.DriverAccess.Platform5\bin"
rd/s/Q "ASCOM.DriverConnect\bin"
rd/s/Q "ASCOM.Internal.Extensions\bin"
rd/s/Q "ASCOM.SettingsProvider\ASCOM.SettingsProvider\bin"
rd/s/Q "ASCOM.SettingsProvider\ASCOM.SettingsProviderSample.CSharp\bin"
rd/s/Q "ASCOM.Utilities\AlpacaDynamicClients\Alpaca Client Device Base Classes\bin"
rd/s/Q "ASCOM.Utilities\AlpacaDynamicClients\Alpaca Client Local Server\bin"
rd/s/Q "ASCOM.Utilities\AlpacaDynamicClients\Alpaca Shared Resources\bin"
rd/s/Q "ASCOM.Utilities\AlpacaDynamicClients\ASCOM.AlpacaDynamicClientManager\bin"
rd/s/Q "ASCOM.Utilities\ASCOM Diagnostics\bin"
rd/s/Q "ASCOM.Utilities\ASCOM.Cache\bin"
rd/s/Q "ASCOM.Utilities\ASCOM.Newtonsoft.Json\bin"
rd/s/Q "ASCOM.Utilities\ASCOM.Utilities\bin"
rd/s/Q "ASCOM.Utilities\ASCOM.Utilities.556\bin"
rd/s/Q "ASCOM.Utilities\FusionLib\bin"
rd/s/Q "ASCOM.Utilities\MigrateProfile\bin"
rd/s/Q "ASCOM.Utilities\Profile Explorer\bin"
rd/s/Q "ASCOM.Utilities.Video\bin"
rd/s/Q "ASCOM.Utilities.Video.NativeHelpers\bin"
rd/s/Q "Common\bin"
rd/s/Q "Driver Inst\InstallerGen\bin"
rd/s/Q "Driver Inst\WinFormsExtras\bin"
rd/s/Q "Drivers and Simulators\ASCOM Device Hub\DeviceHub\bin"
rd/s/Q "Drivers and Simulators\ASCOM Device Hub\MvvmMessenger\bin"
rd/s/Q "Drivers and Simulators\ASCOM.Simulator.Video\bin"
rd/s/Q "Drivers and Simulators\CameraSimulator.NET\CameraSimulator\bin"
rd/s/Q "Drivers and Simulators\CoverCalibrator Simulator\bin"
rd/s/Q "Drivers and Simulators\Dome Simulator .NET\bin"
rd/s/Q "Drivers and Simulators\FilterWheel Simulator .NET\FilterWheelServer\bin"
rd/s/Q "Drivers and Simulators\Focus Simulator 2010\FocuserSimulatorDriver\bin"
rd/s/Q "Drivers and Simulators\ObservingConditions Hub\OCH Driver\bin"
rd/s/Q "Drivers and Simulators\ObservingConditions Hub\OCH Server\bin"
rd/s/Q "Drivers and Simulators\ObservingConditions Hub\OCH Test\bin"
rd/s/Q "Drivers and Simulators\ObservingConditions Simulator\OC Simulator Driver\bin"
rd/s/Q "Drivers and Simulators\ObservingConditions Simulator\OC Simulator Server\bin"
rd/s/Q "Drivers and Simulators\ObservingConditions Simulator\OC Simulator Test\bin"
rd/s/Q "Drivers and Simulators\OpenWeatherMap\OpenWeatherMap\bin"
rd/s/Q "Drivers and Simulators\Rotator Simulator\RotatorDriver\bin"
rd/s/Q "Drivers and Simulators\Rotator Simulator\RotatorServer\bin"
rd/s/Q "Drivers and Simulators\SafetyMonitor Simulator\bin"
rd/s/Q "Drivers and Simulators\SwitchV2 Simulator\SwitchV2Driver\bin"
rd/s/Q "Drivers and Simulators\SwitchV2 Simulator\SwitchServer\bin"
rd/s/Q "Drivers and Simulators\Telescope Simulator .NET\Telescope\bin"
rd/s/Q "Drivers and Simulators\Telescope Simulator .NET\TelescopeSimulator\bin"
rd/s/Q "DriverTemplates\VSIXInstaller\ASCOM.Setup.TemplateWizard\bin"
rd/s/Q "GACInstall\bin"
rd/s/Q "Interfaces\ASCOMExceptions\bin"
rd/s/Q "Releases\ASCOM 6\FinaliseInstall\FinaliseInstall\bin"
rd/s/Q "Releases\ASCOM 6\InstallTemplates\InstallTemplates\bin"
rd/s/Q "Releases\ASCOM 6\SuppressWinErrors\bin"
rd/s/Q "Releases\ASCOM 6\Uninstaller\MigrationSupport\bin"
rd/s/Q "Releases\ASCOM 6\Uninstaller\UninstallASCOM\bin"
rd/s/Q "Remove ASCOM\Find GUIDs\bin"
rd/s/Q "Remove ASCOM\Remove ASCOM\bin"
rd/s/Q "Stand Alone Tester\bin"
rd/s/Q "TestApps\CameraTest\bin"
rd/s/Q "ValidatePlatform\bin"

rd/s/Q "ASCOM Platform Examples\ASCOM.DriverAccess Example\obj"
rd/s/Q "ASCOM Platform Examples\Examples\obj"
rd/s/Q "ASCOM Redirection Policies\ASCOM Redirection Policies\obj"
rd/s/Q "ASCOM.Astrometry\ASCOM.Astrometry\obj"
rd/s/Q "ASCOM.Astrometry\ASCOM.Astrometry556\obj"
rd/s/Q "ASCOM.Astrometry\EarthRotationUpdate\obj"
rd/s/Q "ASCOM.Attributes\obj"
rd/s/Q "ASCOM.Controls\ASCOM.Controls\obj"
rd/s/Q "ASCOM.Controls\ASCOM.Controls.Demo\obj"
rd/s/Q "ASCOM.DeviceInterface\obj"
rd/s/Q "ASCOM.DriverAccess\obj"
rd/s/Q "ASCOM.DriverAccess.Platform5\obj"
rd/s/Q "ASCOM.DriverConnect\obj"
rd/s/Q "ASCOM.Internal.Extensions\obj"
rd/s/Q "ASCOM.SettingsProvider\ASCOM.SettingsProvider\obj"
rd/s/Q "ASCOM.SettingsProvider\ASCOM.SettingsProviderSample.CSharp\obj"
rd/s/Q "ASCOM.Utilities\AlpacaDynamicClients\Alpaca Client Device Base Classes\obj"
rd/s/Q "ASCOM.Utilities\AlpacaDynamicClients\Alpaca Client Local Server\obj"
rd/s/Q "ASCOM.Utilities\AlpacaDynamicClients\Alpaca Shared Resources\obj"
rd/s/Q "ASCOM.Utilities\AlpacaDynamicClients\ASCOM.AlpacaDynamicClientManager\obj"
rd/s/Q "ASCOM.Utilities\ASCOM Diagnostics\obj"
rd/s/Q "ASCOM.Utilities\ASCOM.Cache\obj"
rd/s/Q "ASCOM.Utilities\ASCOM.Newtonsoft.Json\obj"
rd/s/Q "ASCOM.Utilities\ASCOM.Utilities\obj"
rd/s/Q "ASCOM.Utilities\ASCOM.Utilities.556\obj"
rd/s/Q "ASCOM.Utilities\FusionLib\obj"
rd/s/Q "ASCOM.Utilities\MigrateProfile\obj"
rd/s/Q "ASCOM.Utilities\Profile Explorer\obj"
rd/s/Q "ASCOM.Utilities.Video\obj"
rd/s/Q "ASCOM.Utilities.Video.NativeHelpers\obj"
rd/s/Q "Common\obj"
rd/s/Q "Driver Inst\InstallerGen\obj"
rd/s/Q "Driver Inst\WinFormsExtras\obj"
rd/s/Q "Drivers and Simulators\ASCOM Device Hub\DeviceHub\obj"
rd/s/Q "Drivers and Simulators\ASCOM Device Hub\MvvmMessenger\obj"
rd/s/Q "Drivers and Simulators\ASCOM.Simulator.Video\obj"
rd/s/Q "Drivers and Simulators\CameraSimulator.NET\CameraSimulator\obj"
rd/s/Q "Drivers and Simulators\CoverCalibrator Simulator\obj"
rd/s/Q "Drivers and Simulators\Dome Simulator .NET\obj"
rd/s/Q "Drivers and Simulators\FilterWheel Simulator .NET\FilterWheelServer\obj"
rd/s/Q "Drivers and Simulators\Focus Simulator 2010\FocuserSimulatorDriver\obj"
rd/s/Q "Drivers and Simulators\ObservingConditions Hub\OCH Driver\obj"
rd/s/Q "Drivers and Simulators\ObservingConditions Hub\OCH Server\obj"
rd/s/Q "Drivers and Simulators\ObservingConditions Hub\OCH Test\obj"
rd/s/Q "Drivers and Simulators\ObservingConditions Simulator\OC Simulator Driver\obj"
rd/s/Q "Drivers and Simulators\ObservingConditions Simulator\OC Simulator Server\obj"
rd/s/Q "Drivers and Simulators\ObservingConditions Simulator\OC Simulator Test\obj"
rd/s/Q "Drivers and Simulators\OpenWeatherMap\OpenWeatherMap\obj"
rd/s/Q "Drivers and Simulators\Rotator Simulator\RotatorDriver\obj"
rd/s/Q "Drivers and Simulators\Rotator Simulator\RotatorServer\obj"
rd/s/Q "Drivers and Simulators\SafetyMonitor Simulator\obj"
rd/s/Q "Drivers and Simulators\SwitchV2 Simulator\SwitchServer\obj"
rd/s/Q "Drivers and Simulators\SwitchV2 Simulator\SwitchV2Driver\obj"
rd/s/Q "Drivers and Simulators\Telescope Simulator .NET\Telescope\obj"
rd/s/Q "Drivers and Simulators\Telescope Simulator .NET\TelescopeSimulator\obj"
rd/s/Q "DriverTemplates\VSIXInstaller\ASCOM.Setup.TemplateWizard\obj"
rd/s/Q "GACInstall\obj"
rd/s/Q "Help\obj"
rd/s/Q "Interfaces\ASCOMExceptions\obj"
rd/s/Q "Releases\ASCOM 6\FinaliseInstall\FinaliseInstall\obj"
rd/s/Q "Releases\ASCOM 6\InstallTemplates\InstallTemplates\obj"
rd/s/Q "Releases\ASCOM 6\SuppressWinErrors\obj"
rd/s/Q "Releases\ASCOM 6\Uninstaller\MigrationSupport\obj"
rd/s/Q "Releases\ASCOM 6\Uninstaller\UninstallASCOM\obj"
rd/s/Q "Remove ASCOM\Find GUIDs\obj"
rd/s/Q "Remove ASCOM\Remove ASCOM\obj"
rd/s/Q "Stand Alone Tester\obj"
rd/s/Q "TestApps\CameraTest\obj"
rd/s/Q "bin"
rd/s/Q "obj"
rd/s/Q "help\Output"

rd/s/Q "ASCOM.Utilities\Setup"
rd/s/Q "NOVAS\NOVAS-31\CioFile\Win32"
rd/s/Q "NOVAS\NOVAS-31\MakeEph\Win32"
rd/s/Q "NOVAS\NOVAS-31\NOVAS3\Win32"
rd/s/Q "SOFA\Sofa Library\Win32"
rd/s/Q "SOFA\Sofa Test Application\Win32"

rd/s/Q "Drivers and Simulators\FilterWheel Simulator .NET\FilterWheelDriver\bin"
rd/s/Q "NOVAS\NOVAS-31\CioFile\bin"
rd/s/Q "NOVAS\NOVAS-31\MakeEph\bin"
rd/s/Q "NOVAS\NOVAS-31\NOVAS3\bin"
rd/s/Q "SOFA\Sofa Library\bin"
rd/s/Q "SOFA\Sofa Test Application\bin"

rd/s/Q "Drivers and Simulators\FilterWheel Simulator .NET\FilterWheelDriver\obj"
rd/s/Q "NOVAS\NOVAS-31\CioFile\obj"
rd/s/Q "NOVAS\NOVAS-31\MakeEph\obj"
rd/s/Q "NOVAS\NOVAS-31\NOVAS3\obj"
rd/s/Q "SOFA\Sofa Library\obj"
rd/s/Q "SOFA\Sofa Test Application\obj"
rd/s/Q "ValidatePlatform\obj"


del "ASCOM.DeviceInterface\ASCOM.DeviceInterfaces.xml"
