@echo off
echo -
set current=%CD%

call remlink.bat "Drivers and Simulators\Dome Simulator .NET" 
call remlink.bat "Drivers and Simulators\Rotator Simulator\RotatorServer" 
call remlink.bat "Drivers and Simulators\Focus Simulator 2010\FocuserSimulatorDriver" 
call remlink.bat "Drivers and Simulators\CameraSimulator.NET\CameraSimulator" 
call remlink.bat "ASCOM.Astrometry\ASCOM.Astrometry" 
call remlink.bat "ASCOM.Utilities\ASCOM.Utilities" 
call remlink.bat "Interfaces\ASCOMExceptions" 
call remlink.bat "ASCOM.DeviceInterface" 
call remlink.bat "drivers and simulators\safetymonitor simulator\" 
call remlink.bat "Drivers and Simulators\ASCOM.Simulator.Video" 
call remlink.bat "ASCOM.Utilities.Video" 
call remlink.bat "Drivers and Simulators\SwitchV2 Simulator\SwitchServer" 
call remlink.bat "Drivers and Simulators\ObservingConditions Hub\OCH Server" 

call remlink.bat "Drivers and Simulators\ObservingConditions Simulator\OC Simulator Server" 
call remlink.bat "Drivers and Simulators\OpenWeatherMap\OpenWeatherMap" 
call remlink.bat "ASCOM.DriverAccess" 
call remlink.bat "ASCOM.DriverAccess.Platform5" 
call remlink.bat "ASCOM.Utilities\ASCOM.Cache" 
call remlink.bat "ASCOM.Utilities\ASCOM Diagnostics" 
call remlink.bat "ASCOM.Utilities\AlpacaDynamicClients\Alpaca Client Device Base Classes" 
call remlink.bat "ASCOM.Attributes" 
call remlink.bat "ASCOM.Utilities\ASCOM.Newtonsoft.Json" 
call remlink.bat "ASCOM.Utilities\AlpacaDynamicClients\ASCOM.AlpacaDynamicClientManager" 
call remlink.bat "Drivers and Simulators\CoverCalibrator Simulator" 

rem call remlink.bat "Drivers and Simulators\ASCOM Device Hub\TelescopeDriver" 
rem call remlink.bat "Drivers and Simulators\ASCOM Device Hub\DomeDriver" 
rem call remlink.bat "Drivers and Simulators\ASCOM Device Hub\FocuserDriver" 
call remlink.bat "Drivers and Simulators\ASCOM Device Hub\DeviceHub" 
call remlink.bat "ASCOM.Utilities\FusionLib" 
call remlink.bat "ASCOM.Astrometry\ASCOM.Astrometry556\" 
call remlink.bat "ASCOM.SettingsProvider\ASCOM.SettingsProvider" 
call remlink.bat "ASCOM.Controls\ASCOM.Controls" 
call remlink.bat "ASCOM.Utilities\ASCOM.Utilities.556" 
call remlink.bat "ASCOM.Internal.Extensions" 
call remlink.bat "ASCOM.Utilities\MigrateProfile" 
call remlink.bat "GACInstall" 
call remlink.bat "ASCOM.DriverConnect" 
call remlink.bat "Driver Inst\InstallerGen" 
call remlink.bat "ASCOM.Utilities\Profile Explorer" 
call remlink.bat "Drivers and Simulators\FilterWheel Simulator .NET\FilterWheelDriver" 
call remlink.bat "Drivers and Simulators\Rotator Simulator\RotatorServer" 
call remlink.bat "Drivers and Simulators\SwitchV2 Simulator\SwitchServer" 
call remlink.bat "Drivers and Simulators\ObservingConditions Hub\OCH Test" 
call remlink.bat "Drivers and Simulators\ObservingConditions Simulator\OC Simulator Test" 
call remlink.bat "ASCOM.Astrometry\EarthRotationUpdate" 
call remlink.bat "ASCOM.Utilities\AlpacaDynamicClients\Alpaca Shared Resources" 
call remlink.bat "ASCOM.Utilities\AlpacaDynamicClients\Alpaca Client Local Server" 
call remlink.bat "ValidatePlatform" 
rem call remlink.bat "DriverTemplates\ASCOM.Setup.TemplateWizard" 


:end
cd %current%